/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compareToGivenValue;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;



class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void testEmptyArray(){
        int array[] = {};
        assertFalse(App.countCompare(array,2,5,3,4));
    }
    @Test
    public void testEnough(){
        int array[] = {1,2,3,4,5,6,7,8,9};
        assertTrue(App.countCompare(array,0,8,3,4));
    }
    @Test
    public void testNotEnough(){
        int array[] = {1,2,3,4,5,6,7,8,9};
        assertFalse(App.countCompare(array, 0, 8, 6, 5));
    }
    @Test
    public void testExpectedCountTooBig(){
        int array[] = {1,2,3,4};
        assertFalse(App.countCompare(array,0,3,2,8));
    }
}
