/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compareToGivenValue;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    public static boolean countCompare(int array[],int x,int y,int z,int a) {
        /* by given x and y values limits the array indexes that i will look for, after that every value within the limits 
        is compared to the value z, if value>z increase temp, if temp > a return true if not false */
        int temp=0;
        if(array == null){ //if array is empty
            return false;
        }
        if(a > array.length){ //since we can never hit a 
            return false;
        }
        if(y<x){
            int t = x;
            x=y;
            y=t;
        }
        for(int i=x;i<y;i++){
            if(array[i] > z){
                temp++;
            }
        }
        if(temp > a){
            return true;
        }
        else{
            return false;
        }
    }
}
